networks:
  dev:
    external: true
  pg_auth:


services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "postgres"
    networks:
      - pg_auth
    ports:
      - 5432:5432

  app:
    build: .
    container_name: app
    image: app
    environment:
      PG_URL: "postgres://user:pass@postgres:5432/postgres"
    ports:
      - 8080:8080
      - 44044:44044
    networks:
      - dev
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  pg-data:
